Adding scrolling feature
KonradSar/PERNWebsiteAutomatedTesting pull request #3
Opened 2023-02-16 17:16 UTC by KonradSar

ready for code review again

2023-02-20 10:32 UTC, JMiWl requested changes

2023-02-20 10:32 UTC, JMiWl commented on README.md
> +This tests are prepared to execute and maintain test connected with pern.pl website. Using this script user can find out if basic functionalities work properly
Why you don't just add pom file into the repository and put here the instruction how to build the app with it?:)

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/BasesLocationDetailsPage.java
>          webDriverWait = new WebDriverWait(driver, Duration.ofSeconds(7));
I never used this method, but is it static wait for 7 seconds?

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/BasesLocationDetailsPage.java
> +        WebElement webElement = driver.findElement(By.cssSelector(".tytul-obiekt"));
use koluszkiBaseBanner instead of creating this element separately.

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/BasesLocationDetailsPage.java
> +        return logicValue;
You can simplify this method to one line:
return koluszkiBaseBanner.getText().equals("Baza Paliw nr 1 w Koluszkach");

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/CookiesViewPage.java
>          webDriverWait = new WebDriverWait(driver, Duration.ofSeconds(7));
Same question about wait as above.

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/FuelServicesPage.java
> +        WebElement koluszkiLabel = driver.findElement(By.cssSelector("[href='https://www.pern.pl/obiekty/baza-paliw-nr-1-w-koluszkach/']"));
Please move all elements declarations to class parameters.

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/FuelsAndBiocomponentsRequirementsPage.java
>          WebElement requirementsTab = webDriverWait.until(ExpectedConditions.presenceOfElementLocated(dieselFuelsRequirementsBtn));
use var instead of WebElement.

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/FuelsAndBiocomponentsRequirementsPage.java
>          WebElement flashPointValue = driver.findElement(flashPointTableValue);
use var instead of WebElement.

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/FuelsAndBiocomponentsRequirementsPage.java
> +        Actions actions = new Actions(driver);
use var instead of Actions.

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/FuelsAndBiocomponentsRequirementsPage.java
> +        WebElement flashPoint = driver.findElement(By.xpath(".//div[@class='col-8 builder-container__content']/div[@id='faq-simple']/div[2]/div[@id='collapse2']//table//tr[8]"));
use var instead of WebElement.

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/FuelsAndBiocomponentsRequirementsPage.java
> +        WebElement flashPoint = driver.findElement(By.xpath(".//div[@class='col-8 builder-container__content']/div[@id='faq-simple']/div[2]/div[@id='collapse2']//table//tr[8]"));
And move element declaration to the class parameters.

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/FuelsAndBiocomponentsRequirementsPage.java
> +        WebElement flashPoint = driver.findElement(By.xpath(".//div[@class='col-8 builder-container__content']/div[@id='faq-simple']/div[2]/div[@id='collapse2']//table//tr[8]"));
Is there a way to make the xpath shorter?

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/FuelsAndBiocomponentsRequirementsPage.java
> +        }
You can simplify this whole method to one line by just returning:
return flashPoint.getText().contains("55,0")

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/GoogleMapsPage.java
> +        webDriverWait = new WebDriverWait(driver, Duration.ofSeconds(7));
Same question to wait as above:)

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/HeaderPage.java
> +        webDriverWait = new WebDriverWait(driver, Duration.ofSeconds(17));
You know what is this comment already:)

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/HeaderPage.java
> +        WebElement searchInput = webDriverWait.until(ExpectedConditions.presenceOfElementLocated(textInput));
Use var instead of WebElement.

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/HeaderPage.java
> +        Actions actions = new Actions(driver);
User var instead of Actions

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/LaboratoryServicesPage.java
>          WebElement requirementsTab = webDriverWait.until(ExpectedConditions.presenceOfElementLocated(fuelsAndBiocomponentsRequirementsTab));
Use var instead of WebElement

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/MainPage.java
>          WebElement liquidFuelsTab = webDriverWait.until(ExpectedConditions.presenceOfElementLocated(pernFuelsTab));
Use var instead of WebElement.

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/MainPage.java
>          WebElement oilServicesTab = webDriverWait.until(ExpectedConditions.presenceOfElementLocated(oilTab));
Use var instead of WebElement.

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/MainPage.java
> +        WebElement servicesTitle = webDriverWait.until(ExpectedConditions.presenceOfElementLocated(servicesSectionTitle));
Use var instead of WebElement.

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/MainPage.java
> +        WebElement servicesTitle = webDriverWait.until(ExpectedConditions.presenceOfElementLocated(map));
Use var instead of WebElement.

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/MainPage.java
> +        Actions actions = new Actions(driver);
Use var instead of Actions.

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/PageObjects/SearchResultsPage.java
> +        boolean isAnyResult = false;
Simplify this method same as ones above:)

2023-02-20 10:32 UTC, JMiWl commented on src/main/java/Utils/FileReader.java
> +    public void loadFile(String fileLocation) {
You can use @SneakyThrows instead all the catches:)

2023-02-20 10:32 UTC, JMiWl commented on src/test/java/POMTests/BaseTest.java
> +    private static String testDataLocation = "src/configs/Configuration.properties";
Please use:
private static final String TEST_DATA_LOCATION = "src/configs/Configuration.properties";

2023-02-20 10:32 UTC, JMiWl commented on src/test/java/POMTests/BaseTest.java
> +        properties.load(new InputStreamReader(new FileInputStream("src/configs/Configuration.properties"), StandardCharsets.UTF_8));
You have this string declared above - you can use it here:)

2023-02-20 10:32 UTC, JMiWl commented on src/test/java/POMTests/BaseTest.java
> +        Properties properties = new Properties();
var instead of Properties.

2023-02-20 10:32 UTC, JMiWl commented on src/test/java/POMTests/FuelServicesTests.java
> +        //when
I prefer notation:
// When

2023-02-20 10:32 UTC, JMiWl commented on src/test/java/POMTests/FuelServicesTests.java
> +        mainPage.goToFuelServicesPage().selectKoluszkiBaseLocation();
Add empty line before // Then

2023-02-20 10:32 UTC, JMiWl commented on src/test/java/POMTests/FuelServicesTests.java
> +
Remove empty lines.

2023-02-20 10:32 UTC, JMiWl commented on src/test/java/POMTests/FuelServicesTests.java
> +        Assertions.assertTrue(inputValueFromGoogleMapsPage.contains(testDataReader.getPernAddressInputValue().getAddress()));
I prefer to user assertThat(), and probably you can import assert true directly without using Assertions.

2023-03-26 18:15 UTC, closed without merging

2023-03-26 18:15 UTC, KonradSar commented
ready to merge